config/routes.rb
Hirviurheilu::Application.routes.draw do
  scope "(/:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    resource :home

    delete 'logout' => 'user_sessions#destroy', :as => :logout
    get 'login' => 'user_sessions#new', :as => :login
    resource :user_session

    resource :account, :controller => 'users'
    get 'register' => 'users#new', :as => :register
    resources :users
    resource :passwords, only: [:edit, :update]
    get 'reset_password/:reset_hash/edit' => 'reset_passwords#edit', :as => :edit_reset_password
    resource :reset_password

    resources :announcements
    resource :info
    get 'answers' => 'infos#answers', :as => :answers
    get 'sports_info' => 'infos#sports_info'
    resources :feedbacks, only: :new

    resources :prices
    get 'offers/new', to: redirect('/prices')

    resources :cups do
      resources :cup_series
      resources :rifle_cup_series
      resource :medium
    end

    resources :races do
      get 'trap', to: 'nordic_races#trap', as: :trap
      get 'shotgun', to: 'nordic_races#shotgun', as: :shotgun
      get 'rifle_moving', to: 'nordic_races#rifle_moving', as: :rifle_moving
      get 'rifle_standing', to: 'nordic_races#rifle_standing', as: :rifle_standing
      resources :qualification_round_batches, only: :index
      resources :final_round_batches, only: :index
      resources :series do
        get 'rifle', to: 'european_rifles#index', as: :rifle
        resource :start_list, only: :show
      end
      resources :start_lists, only: :index
      resources :team_competitions
      resources :rifle_team_competitions, only: :show
      resources :relays do
        get 'start_list' => 'relays#start_list'
        resources :legs, only: :show
      end
      resource :result_rotation, only: :show
      resource :medium
    end

    resources :series do
      resources :competitors
      resource :start_list
    end

    resources :relays do
      resources :legs
    end

    namespace :admin do
      resources :announcements
      resources :races
      resources :users
      root :to => "index#show"
    end

    namespace :official do
      namespace :limited do
        resources :races do
          resources :competitors
          resources :csv_imports
        end
      end

      resources :cups

      resources :multiple_races, only: [:new, :create]

      resources :races do
        resources :batches
        resource :batch_lists_reset, only: [:show, :destroy]
        resources :qualification_round_batch_lists, only: :index
        resources :final_round_batch_lists, only: :index
        resources :competitor_numbers, only: :index
        get 'nordic_batch_lists_trap', to: 'nordic_batch_lists#trap'
        get 'nordic_batch_lists_shotgun', to: 'nordic_batch_lists#shotgun'
        get 'nordic_batch_lists_rifle_moving', to: 'nordic_batch_lists#rifle_moving'
        get 'nordic_batch_lists_rifle_standing', to: 'nordic_batch_lists#rifle_standing'
        get 'european_batch_lists_trap', to: 'european_batch_lists#trap'
        get 'european_batch_lists_compak', to: 'european_batch_lists#compak'
        get 'european_batch_lists_rifle', to: 'european_batch_lists#rifle'
        resource :batch_list_template, only: :show
        get 'competitor_numbers/:number' => 'competitors#show_by_number'
        put 'competitors/:competitor_id/track_place' => 'competitor_track_places#update'
        delete 'competitors/:competitor_id/track_place' => 'competitor_track_places#destroy'
        resources :competitors, :only => [:create, :update]
        get 'competitors' => 'races#competitors'
        get 'clubs/competitors' => 'clubs#competitors'
        resources :clubs
        put 'correct_estimates' => 'correct_estimates#update', :as => :correct_estimates
        resources :correct_estimates
        resources :race_rights
        post 'estimates_quick_save' => 'quick_saves#save_estimates', :as => :quick_save_estimates
        post 'shots_quick_save' => 'quick_saves#save_shots', :as => :quick_save_shots
        post 'time_quick_save' => 'quick_saves#save_time', :as => :quick_save_time
        post 'qualification_round_shots_quick_save' => 'quick_saves#save_qualification_round_shots', as: :quick_save_qualification_round_shots
        post 'final_round_shots_quick_save' => 'quick_saves#save_final_round_shots', as: :quick_save_final_round_shots
        post 'extra_shots_quick_save' => 'quick_saves#save_extra_shots', as: :quick_save_extra_shots
        post 'no_result_quick_save' => 'quick_saves#save_no_result', :as => :quick_save_no_result
        patch 'national_records' => 'national_records#update_all', as: :update_national_records
        resources :national_records, only: :index
        resources :quick_saves
        resource :finish_race
        get 'export/success' => 'exports#success'
        get 'export/error' => 'exports#error'
        resources :relays
        resources :team_competitions
        resources :csv_imports
        resource :start_list
        resource :csv_export
        resource :competitor_copying
        resources :shooting_by_batches, only: :index
        get 'nordic_trap', to: 'nordic_race_shots#trap', as: :nordic_trap
        get 'nordic_shotgun', to: 'nordic_race_shots#shotgun', as: :nordic_shotgun
        get 'nordic_rifle_moving', to: 'nordic_race_shots#rifle_moving', as: :nordic_rifle_moving
        get 'nordic_rifle_standing', to: 'nordic_race_shots#rifle_standing', as: :nordic_rifle_standing
        get 'european_trap', to: 'european_race_shots#trap', as: :european_trap
        get 'european_compak', to: 'european_race_shots#compak', as: :european_compak
        get 'european_rifle', to: 'european_race_shots#rifle', as: :european_rifle
        resource :printing, only: :show
      end

      resources :series do
        resource :qualification_round_batch_list, only: [:show, :create]
        resource :final_round_batch_list, only: [:show, :create]
        resources :competitors, :except => :create
        resources :age_groups
        resource :start_list
        resources :shots
        resources :estimates
        resources :times
      end

      resources :relays do
        resources :relay_teams
        post 'relay_estimate_quick_save' => 'relay_quick_saves#estimate',
          :as => :relay_estimate_quick_save
        post 'relay_misses_quick_save' => 'relay_quick_saves#misses',
          :as => :relay_misses_quick_save
        post 'relay_time_quick_save' => 'relay_quick_saves#time',
          :as => :relay_time_quick_save
        post 'relay_adjustment_quick_save' => 'relay_quick_saves#adjustment',
          :as => :relay_adjustment_quick_save
        post 'relay_estimate_penalties_adjustment_quick_save' => 'relay_quick_saves#estimate_penalties_adjustment',
             :as => :relay_estimate_penalties_adjustment_quick_save
        post 'relay_shooting_penalties_adjustment_quick_save' => 'relay_quick_saves#shooting_penalties_adjustment',
             :as => :relay_shooting_penalties_adjustment_quick_save
        resources :relay_quick_saves
        resource :finish_relay
      end

      root :to => "index#show"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do
      namespace :official do
        resources :races, only: [:show] do
          resource :health, only: :show
          resources :relays, only: [] do
            put '/relay_teams/:team_number/legs/:leg/arrival_time' => 'relay_arrival_times#update'
          end
          put '/competitors/:competitor_number/start_time' => 'start_times#update'
          put '/competitors/:competitor_number/shooting_start_time' => 'shooting_start_times#update'
          put '/competitors/:competitor_number/shooting_finish_time' => 'shooting_finish_times#update'
          put '/competitors/:competitor_number/arrival_time' => 'arrival_times#update'
          put '/competitors/:competitor_number/shots' => 'shots#update_all'
          put '/competitors/:competitor_number/extra_shots' => 'extra_shots#update_all'
          put '/competitors/:competitor_number/shots/:shot_number' => 'shots#update'
          put '/competitors/:competitor_number/extra_shots/:shot_number' => 'extra_shots#update'
        end
      end

      namespace :public do
        get 'home', to: 'home#index'
        resources :announcements, only: [:index, :show]
        resources :districts, only: :index
        resources :races, only: [:index, :show] do
          resources :series, only: [:show] do
            resource :start_list, only: :show
            get 'rifle', to: 'european_rifles#show'
          end
          resources :rifle_team_competitions, only: [:show]
          resources :team_competitions, only: [:show]
          resources :relays, only: [:show]
          resources :times, only: :index
          resource :press, only: :show
          resources :qualification_round_batches, only: :index
          resources :final_round_batches, only: :index
          get 'trap', to: 'nordic_races#trap'
          get 'shotgun', to: 'nordic_races#shotgun'
          get 'rifle_moving', to: 'nordic_races#rifle_moving'
          get 'rifle_standing', to: 'nordic_races#rifle_standing'
          get '/competitors/:competitor_number', to: 'competitors#show'
        end
        resources :recent_races, only: :index
        resources :cups, only: :show do
          resources :cup_series, only: :show
          resources :rifle_cup_series, only: :show
        end
        resources :feedbacks, only: :create
      end
    end
  end

  get '/:locale' => 'home#show', :locale => /#{I18n.available_locales.join('|')}/
  root :to => "home#show"
end

app/controllers/api/v2/official/arrival_times_controller.rb
class Api::V2::Official::ArrivalTimesController < Api::V2::Official::TimesBaseController
  private

  def time_field
    :arrival_time
  end
end

app/controllers/api/v2/official/extra_shots_controller.rb
class Api::V2::Official::ExtraShotsController < Api::V2::Official::ShotsBaseController
  before_action :find_and_validate_race, :find_and_validate_competitor
  before_action :validate_shot_value, :validate_shot_number, only: :update

  def update
    shots = build_shots @competitor.extra_shots
    @competitor.extra_shots = shots
    @competitor.save!
    render status: 200, json: { shots: shots }
  end

  def update_all
    return render status: 400, json: { errors: ['shots missing from request body'] } unless params[:shots]
    return render status: 400, json: { errors: ['invalid shots value'] } unless params[:shots].is_a?(Array)
    @competitor.extra_shots = params[:shots]
    if @competitor.save
      render status: 200, json: { shots: @competitor.extra_shots }
    else
      render status: 400, json: { errors: @competitor.errors.full_messages }
    end
  end

  private

  def validate_shot_number
    @shot_number = params[:shot_number].to_i
    return_error 400, 'invalid shot number' if @shot_number == 0
  end
end

app/controllers/api/v2/official/healths_controller.rb
class Api::V2::Official::HealthsController < Api::V2::Official::OfficialApiBaseController
  before_action :find_and_validate_race

  def show
    render json: { race: @race.name }
  end
end

app/controllers/api/v2/official/official_api_base_controller.rb
class Api::V2::Official::OfficialApiBaseController < Api::V2::ApiBaseController
  private

  def find_and_validate_race
    @race = Race.where(id: params[:race_id]).first
    return return_error 404, 'race not found' unless @race
    return_error 401 if @race.api_secret.blank? || @race.api_secret != request.env['HTTP_AUTHORIZATION']
  end

  def return_error(status, error_message = nil)
    return render status: status, json: { errors: [error_message] } if error_message
    render status: status, body: nil
  end
end

app/controllers/api/v2/official/relay_arrival_times_controller.rb
class Api::V2::Official::RelayArrivalTimesController < Api::V2::Official::OfficialApiBaseController
  before_action :find_and_validate_race

  def update
    @relay = @race.relays.where(id: params[:relay_id]).first
    return render status: 404, json: { errors: ['relay not found'] } unless @relay
    return render status: 400, json: { errors: ['cannot use api for relay that has no start time'] } unless @relay.start_time
    @relay_team = @relay.relay_teams.where(number: params[:team_number]).first
    return render status: 404, json: { errors: ['relay team not found'] } unless @relay_team
    leg = params[:leg].to_i
    return render status: 400, json: { errors: ['invalid leg number'] } if leg <= 0 || leg > @relay.legs_count
    @ms_since_midnight = params[:ms_since_midnight]
    return render status: 400, json: { errors: ['ms_since_midnight missing'] } unless @ms_since_midnight
    return render status: 400, json: { errors: ['ms_since_midnight cannot be before relay start'] } if ms_before_relay_start
    relay_competitor = @relay_team.relay_competitors.where(leg: leg).first
    return render status: 404, json: { errors: ['relay competitor not found'] } unless relay_competitor
    relay_competitor.arrival_time = resolve_competitor_time
    if relay_competitor.save
      relative_time = relay_competitor.arrival_time.strftime('%H:%M:%S')
      render status: 200, json: { relative_time: relative_time }
    else
      render status: 400, json: { errors: relay_competitor.errors.full_messages }
    end
  end

  private

  def ms_before_relay_start
    @ms_since_midnight < 1000 * (60 * 60 * @relay.start_time.hour + 60 * @relay.start_time.min)
  end

  def resolve_competitor_time
    secs_since_midnight = @ms_since_midnight / 1000
    relay_advance = {hours: -@relay.start_time.hour, minutes: -@relay.start_time.min}
    ((Time.now.beginning_of_day + secs_since_midnight.seconds).advance(relay_advance)).strftime('%H:%M:%S')
  end
end

app/controllers/api/v2/official/shooting_finish_times_controller.rb
class Api::V2::Official::ShootingFinishTimesController < Api::V2::Official::TimesBaseController
  private

  def time_field
    :shooting_finish_time
  end
end

app/controllers/api/v2/official/shooting_start_times_controller.rb
class Api::V2::Official::ShootingStartTimesController < Api::V2::Official::TimesBaseController
  private

  def time_field
    :shooting_start_time
  end
end

app/controllers/api/v2/official/shots_base_controller.rb
class Api::V2::Official::ShotsBaseController < Api::V2::Official::OfficialApiBaseController
  private

  def validate_shot_value
    @shot_value = params[:value]
    return_error 400, 'invalid shot value' if Competitor.invalid_shot? @shot_value, @race.sport.best_shot_value
  end

  def find_and_validate_competitor
    @competitor = @race.competitors.where(number: params[:competitor_number]).first
    return_error 404, 'competitor not found' unless @competitor
  end

  def build_shots(current_shots)
    shots = current_shots || []
    shots[@shot_number - 1] = @shot_value
    shots.map {|shot| shot || 0 }
  end
end

app/controllers/api/v2/official/shots_controller.rb
class Api::V2::Official::ShotsController < Api::V2::Official::ShotsBaseController
  before_action :find_and_validate_race, :find_and_validate_competitor
  before_action :validate_shot_value, :validate_shot_number, only: :update

  def update
    shots = build_shots @competitor.shots
    @competitor.shots = shots
    if @competitor.save
      render status: 200, json: { shots: shots }
    else
      render status: 400, json: { errors: @competitor.errors.full_messages }
    end
  end

  def update_all
    return render status: 400, json: { errors: ['shots missing from request body'] } unless params[:shots]
    return render status: 400, json: { errors: ['invalid shots value'] } unless params[:shots].is_a?(Array)
    @competitor.shots = params[:shots]
    if @competitor.save
      render status: 200, json: { shots: @competitor.shots }
    else
      render status: 400, json: { errors: @competitor.errors.full_messages }
    end
  end

  private

  def validate_shot_number
    @shot_number = params[:shot_number].to_i
    return_error 400, 'invalid shot number' if @shot_number == 0 || @shot_number > @race.sport.shot_count
  end
end

app/controllers/api/v2/official/start_times_controller.rb
class Api::V2::Official::StartTimesController < Api::V2::Official::TimesBaseController
  private

  def time_field
    :start_time
  end
end

app/controllers/api/v2/official/times_base_controller.rb
class Api::V2::Official::TimesBaseController < Api::V2::Official::OfficialApiBaseController
  before_action :find_and_validate_race

  def update
    return render status: 404, json: { errors: ['competitor not found'] } unless competitor
    return render status: 400, json: { errors: ['ms_since_midnight missing'] } unless ms_since_midnight
    return render status: 400, json: { errors: ['ms_since_midnight cannot be before race start'] } if ms_before_race_start
    competitor[time_field] = resolve_competitor_time
    if competitor.save
      real_time = competitor.real_time(time_field).strftime('%H:%M:%S')
      relative_time = competitor[time_field].strftime('%H:%M:%S')
      render status: 200, json: { real_time: real_time, relative_time: relative_time }
    else
      render status: 400, json: { errors: competitor.errors.full_messages }
    end
  end

  private

  def competitor
    @competitor ||= @race.competitors.where(number: params[:competitor_number]).first
  end

  def ms_before_race_start
    ms_since_midnight < 1000 * (60 * 60 * @race.start_time.hour + 60 * @race.start_time.min)
  end

  def resolve_competitor_time
    secs_since_midnight = ms_since_midnight / 1000
    race_advance = {hours: -@race.start_time.hour, minutes: -@race.start_time.min}
    ((Time.now.beginning_of_day + secs_since_midnight.seconds).advance(race_advance)).strftime('%H:%M:%S')
  end

  def ms_since_midnight
    params[:ms_since_midnight]
  end
end

app/views/official/competitors/_basic_fields.html.haml
- age_group_style = f.object.series.age_groups.empty? ? 'display:none;' : ''
.form__field.form__field--md.row
  .col-xs-12.col-sm-3= f.label :series_id
  .col-xs-12.col-sm-9= f.select :series_id, options_from_collection_for_select(@series_menu_options, :id, :name, f.object.series.id), {}, onchange: 'change_series(this.value)'
.form__field.form__field--md.row#age_groups_span{style: age_group_style}
  .col-xs-12.col-sm-3= f.label :age_group_id, t("age_group.#{@series.sport.shooting? ? 'shooting_race' : 'three_sports_race'}")
  .col-xs-12.col-sm-9
    - include_blank = !f.object.new_record? && f.object.series.competitors_only_to_age_groups? && f.object.age_group.nil?
    = f.collection_select :age_group_id, f.object.series.age_groups_with_main_series, :id, :name, include_blank: include_blank
    %span#age_groups_spinner{style: 'display:none;'}
      = image_tag 'spinner.gif'
      Odota hetki...
.form__field.row
  .col-xs-12.col-sm-3= f.label :first_name
  .col-xs-12.col-sm-9= f.text_field :first_name
.form__field.row
  .col-xs-12.col-sm-3= f.label :last_name
  .col-xs-12.col-sm-9= f.text_field :last_name
.form__field.row
  .col-xs-12.col-sm-3= f.label :unofficial
  .col-xs-12.col-sm-9= f.check_box :unofficial
- club_level = f.object.race.club_level
.form__field.form__field--md.row
  .col-xs-12.col-sm-3= f.label :club_id, club_title(f.object.series.race)
  - menu_style = f.object.race.clubs.empty? ? 'display:none;' : ''
  .col-xs-12.col-sm-9
    = select_tag :club_id, options_from_collection_for_select(f.object.race.clubs,
      :id, :name, f.object.club_id), prompt: t("official.competitors.new.club_selection_prompt_#{club_level}"), style: menu_style
    = text_field_tag :club_name, '', placeholder: t("official.competitors.new.new_club_hint_#{club_level}")
- if @series.race.has_team_competitions_with_team_names?
  .form__field.row
    .col-xs-12.col-sm-3
      .form__help-label
        = f.label :team_name
        %a.help#team_name_help{href: "javascript:void(0);"} ?
    .col-xs-12.col-sm-9= f.text_field :team_name
  = render :partial => 'official/shared/team_name_help_dialog'
- if @series.sport.european?
  .form__field.row
    .col-xs-12.col-sm-3= f.label :only_rifle
    .col-xs-12.col-sm-9= f.check_box :only_rifle
- if f.object.new_record? && !@series.sport.shooting?
  - number_style = 'display:none;'
  - if f.object.series.has_start_list?
    - number_style = ''
  #number_span{style: number_style}
    .form__field.form__field--sm.row
      .col-xs-12.col-sm-3= f.label :number
      .col-xs-12.col-sm-9= f.number_field :number
    .form__field.form__field--sm.row
      .col-xs-12.col-sm-3= f.label :start_time
      - start_time = time_print(f.object.start_time, true, '')
      .col-xs-12.col-sm-9= f.text_field :start_time, value: start_time
:javascript
  $('#club_id').on('change', show_club_name_field);

  function show_club_name_field() {
     if ($('#club_id').prop('selectedIndex') == 0) {
       $('#club_name').show();
     } else {
       $('#club_name').hide();
     }
  }

  function change_series(series_id) {
    reload_age_groups(series_id);
    reload_number_and_start_time_and_link(series_id);
  }

  function reload_number_and_start_time_and_link(series_id) {
    $.getJSON('/series/' + series_id, function(series) {
      if (#{@series.sport.start_list?}) {
        if(series.has_start_list) {
          $('#competitor_number').val(series.next_start_number);
          $('#competitor_start_time').val(series.next_start_time.substring(11, 19));
          $('#number_span').show();
        } else {
          $('#competitor_number').val('');
          $('#competitor_start_time').val('');
          $('#number_span').hide();
        }
      }
      $('#back_to_series').attr('href', '/official/series/' + series_id + '/competitors');
      $('#back_to_series #series_name').text(series.name);
    });
  }

  show_club_name_field();
= render :partial => 'official/shared/reload_age_groups_js'
= render :partial => 'shared/help_dialog_opener'

app/views/official/competitors/create_error.js.erb
$('.message--success').hide();
$('#spinner').hide();
$('.message--error').text("<%= @competitor.errors.full_messages.join(". ") + "." %>");
$('.message--error').show();

app/views/official/competitors/create_error_start_list.js.erb
$("#status_new").html("<span class='error'>Virhe!</span>");
$('div#update_error').addClass("error");
$('div#update_error').text("<%= @competitor.errors.full_messages.join(". ") + "." %>");
$('div#update_error').show();

app/views/official/competitors/edit.html.haml
= content_for(:title, full_name(@competitor))
%h2= yield :title
= render partial: "shared/form_errors", locals: { item: @competitor }
= form_for([:official, @competitor.series, @competitor], html: { class: 'form form--competitor' }) do |f|
  = render partial: "basic_fields", locals: { f: f }
  - if @series.sport.nordic?
    = render partial: 'nordic_form_fields', locals: { f: f }
  - elsif @series.sport.european?
    = render partial: 'european_form_fields', locals: { f: f }
  - elsif @series.sport.shooting?
    = render partial: 'shooting_race_form_fields', locals: { f: f }
  - elsif @series.sport.start_list? && @series.has_start_list?
    = render partial: 'three_sports_race_form_fields', locals: { f: f }
  - else
    = hidden_field_tag :no_times, true
  .form__field.row
    .col-xs-12.col-sm-3
      %label Tila
    .col-xs-12.col-sm-9
      = f.radio_button :no_result_reason, ''
      Normaali
      = f.radio_button :no_result_reason, Competitor::DNS
      = t '.dns'
      = f.radio_button :no_result_reason, Competitor::DNF
      = t '.dnf'
      = f.radio_button :no_result_reason, Competitor::DQ
      = t '.dq'
  .form__buttons
    = submit_tag t(:save), class: 'button button--primary'
.buttons.buttons--nav
  = link_to t('.back_to_series_competitor_list', :series_name => @series.name), official_series_competitors_path(@series), class: 'button button--back'
  = link_to t('.delete_competitor'), official_series_competitor_path(@competitor.series_id, @competitor),
    data: { confirm: t('.remove_confirmation') }, method: :delete, class: 'button button--danger'

app/views/official/competitors/index.html.haml
- content_for :title, "#{@series.race.name} - #{@series.name} - #{t('.title')}"
%h2 #{@series.name} - #{t('.title')}
- content_for :sub_sub_menu do
  = render layout: 'menus/series_sub_menu', locals: { race: @series.race, series_id: @series.id } do |series| official_series_competitors_path(series) end
- if @series.competitors.empty?
  .message.message--info= t('.no_competitors_in_series')
- else
  - if @series.race.sport.start_list?
    - unless @series.has_start_list?
      .message.message--info= t('.create_start_list_info')
    - unless @series.some_competitor_has_arrival_time? || @series.race.start_order == Race::START_ORDER_MIXED
      - start_list_title = @series.has_start_list? ? t('.create_new_start_list') : t('.create_start_list')
      %h3= start_list_title
      = flash_error
      = flash_success
      = render :partial => 'shared/form_errors', locals: { item: @series }
      = form_for([:official, @series], url: official_series_start_list_path, html: { onsubmit: "return warnRerun(#{@series.has_start_list?})", class: 'form' }) do |f|
        .form__field.form__field--sm.row
          .col-xs-12.col-sm-3= f.label :first_number
          .col-xs-12.col-sm-9= f.number_field :first_number
        .form__field.row
          .col-xs-12.col-sm-3
            %label Kilpailun alkamisaika
          .col-xs-12.col-sm-9= time_print @series.race.start_time
        .form__field.form__field--sm.row
          .col-xs-12.col-sm-3= f.label :start_time
          .col-xs-12.col-sm-9
            = start_days_form_field(f, @series)
            %span#series_start_time_row
              = f.time_select :start_time, :include_seconds => true, :include_blank => true
              (00:00:00-pohjainen)
        .form__field.row
          .col-xs-12.col-sm-3
            %label Sarjan todellinen lähtöaika
          .col-xs-12.col-sm-9#real_start_time
        .form__field.row
          .col-xs-12.col-sm-3
            %label #{t "order_method"}:
          .col-xs-12.col-sm-9
            = radio_button_tag :order_method, Series::START_LIST_ADDING_ORDER, Series::START_LIST_ADDING_ORDER == @order_method
            = t "order_method_#{Series::START_LIST_ADDING_ORDER}"
            = radio_button_tag :order_method, Series::START_LIST_RANDOM, Series::START_LIST_RANDOM == @order_method
            = t "order_method_#{Series::START_LIST_RANDOM}"
        .form__buttons
          = submit_tag start_list_title, class: 'button button--primary'
      %h3= t('.added_competitors')
  = render partial: 'official/competitors/list', locals: { series: @series }
.buttons
  - add_title = @series.competitors.empty? ? t('.add_competitor') : t('.add_new_competitor')
  = link_to add_title, new_official_series_competitor_path(@series), class: 'button button--add'
  - if @series.has_start_list?
    = link_to t(:download_start_list_pdf), series_start_list_path(@series, format: 'pdf'), class: 'button button--pdf'
  = link_to t('official.add_competitors_from_csv_file'), new_official_race_csv_import_path(@series.race), class: 'button'
= render layout: 'menus/series_sub_menu', locals: { race: @series.race, series_id: @series.id, mobile: true } do |series|
  = official_series_competitors_path(series)
.buttons.buttons--nav
  = link_to t(:back_to_official_race_page), official_race_path(@series.race), class: 'button button--back'
:javascript
  var raceHours = #{@series.race.start_time.hour};
  var raceMins = #{@series.race.start_time.min};
  var raceSecs = #{@series.race.start_time.sec};
  function warnRerun(rerun) {
    if (rerun) {
      return confirm('Haluatko varmasti luoda uuden lähtölistan kilpailijoille? ' +
        'Nykyiset lähtönumerot ja -ajat korvataan uusilla.');
    }
    return true;
  }
  function calculateRealStartTime() {
    var seriesSecs = parseInt($('#series_start_time_6i').val(), 10) + raceSecs;
    var seriesMins = parseInt($('#series_start_time_5i').val(), 10) + raceMins;
    var extraHours = Math.floor(seriesMins / 60);
    seriesMins %= 60;
    var seriesHours = parseInt($('#series_start_time_4i').val(), 10) + raceHours + extraHours;
    $('#real_start_time').text(padNumber(seriesHours) + ':' + padNumber(seriesMins) + ':' + padNumber(seriesSecs));
  }
  function padNumber(number) {
    return number < 10 ? '0' + number : number;
  }
  $('#series_start_time_row').on('change', 'select', function () {
    calculateRealStartTime();
  });
  $(document).ready(function () {
    calculateRealStartTime();
  });

app/views/official/competitors/update_error.js.erb
<% error_msg = @competitor.errors.full_messages.join(". ") + "." %>
updateInlineMessage("#status_<%= @competitor.id %>", 'error', '<%= t :error %>: <%= error_msg %>')