config/routes.rb
Hirviurheilu::Application.routes.draw do
  scope "(/:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    resource :home

    delete 'logout' => 'user_sessions#destroy', :as => :logout
    get 'login' => 'user_sessions#new', :as => :login
    resource :user_session

    resource :account, :controller => 'users'
    get 'register' => 'users#new', :as => :register
    resources :users
    resource :passwords, only: [:edit, :update]
    get 'reset_password/:reset_hash/edit' => 'reset_passwords#edit', :as => :edit_reset_password
    resource :reset_password

    resources :announcements
    resource :info
    get 'answers' => 'infos#answers', :as => :answers
    get 'sports_info' => 'infos#sports_info'
    resources :feedbacks, only: :new

    resources :prices
    get 'offers/new', to: redirect('/prices')

    resources :cups do
      resources :cup_series
      resources :rifle_cup_series
      resource :medium
    end

    resources :races do
      get 'trap', to: 'nordic_races#trap', as: :trap
      get 'shotgun', to: 'nordic_races#shotgun', as: :shotgun
      get 'rifle_moving', to: 'nordic_races#rifle_moving', as: :rifle_moving
      get 'rifle_standing', to: 'nordic_races#rifle_standing', as: :rifle_standing
      resources :qualification_round_batches, only: :index
      resources :final_round_batches, only: :index
      resources :series do
        get 'rifle', to: 'european_rifles#index', as: :rifle
        resource :start_list, only: :show
      end
      resources :start_lists, only: :index
      resources :team_competitions
      resources :rifle_team_competitions, only: :show
      resources :relays do
        get 'start_list' => 'relays#start_list'
        resources :legs, only: :show
      end
      resource :result_rotation, only: :show
      resource :medium
    end

    resources :series do
      resources :competitors
      resource :start_list
    end

    resources :relays do
      resources :legs
    end

    namespace :admin do
      resources :announcements
      resources :races
      resources :users
      root :to => "index#show"
    end

    namespace :official do
      namespace :limited do
        resources :races do
          resources :competitors
          resources :csv_imports
        end
      end

      resources :cups

      resources :multiple_races, only: [:new, :create]

      resources :races do
        resources :batches
        resource :batch_lists_reset, only: [:show, :destroy]
        resources :qualification_round_batch_lists, only: :index
        resources :final_round_batch_lists, only: :index
        resources :competitor_numbers, only: :index
        get 'nordic_batch_lists_trap', to: 'nordic_batch_lists#trap'
        get 'nordic_batch_lists_shotgun', to: 'nordic_batch_lists#shotgun'
        get 'nordic_batch_lists_rifle_moving', to: 'nordic_batch_lists#rifle_moving'
        get 'nordic_batch_lists_rifle_standing', to: 'nordic_batch_lists#rifle_standing'
        get 'european_batch_lists_trap', to: 'european_batch_lists#trap'
        get 'european_batch_lists_compak', to: 'european_batch_lists#compak'
        get 'european_batch_lists_rifle', to: 'european_batch_lists#rifle'
        resource :batch_list_template, only: :show
        get 'competitor_numbers/:number' => 'competitors#show_by_number'
        put 'competitors/:competitor_id/track_place' => 'competitor_track_places#update'
        delete 'competitors/:competitor_id/track_place' => 'competitor_track_places#destroy'
        resources :competitors, :only => [:create, :update]
        get 'competitors' => 'races#competitors'
        get 'clubs/competitors' => 'clubs#competitors'
        resources :clubs
        put 'correct_estimates' => 'correct_estimates#update', :as => :correct_estimates
        resources :correct_estimates
        resources :race_rights
        post 'estimates_quick_save' => 'quick_saves#save_estimates', :as => :quick_save_estimates
        post 'shots_quick_save' => 'quick_saves#save_shots', :as => :quick_save_shots
        post 'time_quick_save' => 'quick_saves#save_time', :as => :quick_save_time
        post 'qualification_round_shots_quick_save' => 'quick_saves#save_qualification_round_shots', as: :quick_save_qualification_round_shots
        post 'final_round_shots_quick_save' => 'quick_saves#save_final_round_shots', as: :quick_save_final_round_shots
        post 'extra_shots_quick_save' => 'quick_saves#save_extra_shots', as: :quick_save_extra_shots
        post 'no_result_quick_save' => 'quick_saves#save_no_result', :as => :quick_save_no_result
        patch 'national_records' => 'national_records#update_all', as: :update_national_records
        resources :national_records, only: :index
        resources :quick_saves
        resource :finish_race
        get 'export/success' => 'exports#success'
        get 'export/error' => 'exports#error'
        resources :relays
        resources :team_competitions
        resources :csv_imports
        resource :start_list
        resource :csv_export
        resource :competitor_copying
        resources :shooting_by_batches, only: :index
        get 'nordic_trap', to: 'nordic_race_shots#trap', as: :nordic_trap
        get 'nordic_shotgun', to: 'nordic_race_shots#shotgun', as: :nordic_shotgun
        get 'nordic_rifle_moving', to: 'nordic_race_shots#rifle_moving', as: :nordic_rifle_moving
        get 'nordic_rifle_standing', to: 'nordic_race_shots#rifle_standing', as: :nordic_rifle_standing
        get 'european_trap', to: 'european_race_shots#trap', as: :european_trap
        get 'european_compak', to: 'european_race_shots#compak', as: :european_compak
        get 'european_rifle', to: 'european_race_shots#rifle', as: :european_rifle
        resource :printing, only: :show
      end

      resources :series do
        resource :qualification_round_batch_list, only: [:show, :create]
        resource :final_round_batch_list, only: [:show, :create]
        resources :competitors, :except => :create
        resources :age_groups
        resource :start_list
        resources :shots
        resources :estimates
        resources :times
      end

      resources :relays do
        resources :relay_teams
        post 'relay_estimate_quick_save' => 'relay_quick_saves#estimate',
          :as => :relay_estimate_quick_save
        post 'relay_misses_quick_save' => 'relay_quick_saves#misses',
          :as => :relay_misses_quick_save
        post 'relay_time_quick_save' => 'relay_quick_saves#time',
          :as => :relay_time_quick_save
        post 'relay_adjustment_quick_save' => 'relay_quick_saves#adjustment',
          :as => :relay_adjustment_quick_save
        post 'relay_estimate_penalties_adjustment_quick_save' => 'relay_quick_saves#estimate_penalties_adjustment',
             :as => :relay_estimate_penalties_adjustment_quick_save
        post 'relay_shooting_penalties_adjustment_quick_save' => 'relay_quick_saves#shooting_penalties_adjustment',
             :as => :relay_shooting_penalties_adjustment_quick_save
        resources :relay_quick_saves
        resource :finish_relay
      end

      root :to => "index#show"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do
      namespace :official do
        resources :races, only: [:show] do
          resource :health, only: :show
          resources :relays, only: [] do
            put '/relay_teams/:team_number/legs/:leg/arrival_time' => 'relay_arrival_times#update'
          end
          put '/competitors/:competitor_number/start_time' => 'start_times#update'
          put '/competitors/:competitor_number/shooting_start_time' => 'shooting_start_times#update'
          put '/competitors/:competitor_number/shooting_finish_time' => 'shooting_finish_times#update'
          put '/competitors/:competitor_number/arrival_time' => 'arrival_times#update'
          put '/competitors/:competitor_number/shots' => 'shots#update_all'
          put '/competitors/:competitor_number/extra_shots' => 'extra_shots#update_all'
          put '/competitors/:competitor_number/shots/:shot_number' => 'shots#update'
          put '/competitors/:competitor_number/extra_shots/:shot_number' => 'extra_shots#update'
        end
      end

      namespace :public do
        get 'home', to: 'home#index'
        resources :announcements, only: [:index, :show]
        resources :districts, only: :index
        resources :races, only: [:index, :show] do
          resources :series, only: [:show] do
            resource :start_list, only: :show
            get 'rifle', to: 'european_rifles#show'
          end
          resources :rifle_team_competitions, only: [:show]
          resources :team_competitions, only: [:show]
          resources :relays, only: [:show]
          resources :times, only: :index
          resource :press, only: :show
          resources :qualification_round_batches, only: :index
          resources :final_round_batches, only: :index
          get 'trap', to: 'nordic_races#trap'
          get 'shotgun', to: 'nordic_races#shotgun'
          get 'rifle_moving', to: 'nordic_races#rifle_moving'
          get 'rifle_standing', to: 'nordic_races#rifle_standing'
          get '/competitors/:competitor_number', to: 'competitors#show'
        end
        resources :recent_races, only: :index
        resources :cups, only: :show do
          resources :cup_series, only: :show
          resources :rifle_cup_series, only: :show
        end
        resources :feedbacks, only: :create
      end
    end
  end

  get '/:locale' => 'home#show', :locale => /#{I18n.available_locales.join('|')}/
  root :to => "home#show"
end

app/controllers/cup_series_controller.rb
class CupSeriesController < ApplicationController
  before_action :assign_cup, :assign_cup_series_by_id

  def show
    @is_cup = true
    @is_cup_series = true
    render_show
  end

  private

  def assign_cup
    @id = params[:cup_id]
    @cup = Cup.where(id: @id).includes([:cup_series, races: [series: [competitors: [:age_group, :club, :series]]]]).first
    render 'errors/cup_not_found' unless @cup
  end

  def render_show
    use_react
    respond_to do |format|
      format.html { render layout: true, html: '' }
      format.pdf do
        render :pdf => "#{@cup_series.name}-tulokset", :layout => true, :margin => pdf_margin,
               :header => pdf_header("#{@cup.name} - #{@cup_series.name}\n"), :footer => pdf_footer,
               :orientation => 'Landscape', disable_smart_shrinking: true
      end
    end
  end
end

app/views/cup_series/_cup_series_results+mobile.haml
- show_series_name = !@cup_series.has_single_series_with_same_name?
.result-cards
  - @cup_series.ordered_competitors.each_with_index do |cc, i|
    .card{class: i % 2 == 0 ? 'card--odd' : ''}
      .card__number #{i + 1}.
      .card__middle
        .card__name
          = full_name(cc)
          - if show_series_name
            (#{cc.series_name})
        .card__middle-2{style: 'display: none'}
          - @cup.races.each do |race|
            - c = cc.competitor_for_race(race)
            - if c
              %div
                = race.name
                = points_print(c)
      .card__main-value= cup_points_print(cc)

app/views/cup_series/_cup_series_results.haml
- is_pdf = defined?(pdf)
- show_series_name = !cup_series.has_single_series_with_same_name?
- competitors = @is_rifle_cup_series ? cup_series.european_rifle_results : cup_series.results
- if competitors.empty?
  .message.message--info Tähän sarjaan ei ole lisätty kilpailijoita
- else
  - race_count = @cup.races.count
  - top_competitions = @cup.top_competitions
  %table.results-table
    %thead
      %tr
        %th &nbsp;
        %th= t 'activerecord.models.competitor.one'
        - if show_series_name
          %th= t 'activerecord.models.series.one'
        - @cup.races.each do |race|
          %th= race.name
        %th= t :total_points
    - competitors.each_with_index do |cc, i|
      - emphasize_limit = cc.min_points_to_emphasize race_count, top_competitions, @is_rifle_cup_series
      %tr{id: "comp_#{i+1}", class: i % 2 == 0 ? 'odd' : ''}
        %td #{i + 1}.
        %td
          = cc.last_name
          = cc.first_name
        - if show_series_name
          %td= cc.series_names
        - @cup.races.each do |race|
          - c = cc.competitor_for_race(race)
          %td.center
            - if c
              - if c.no_result_reason
                = no_result_reason_print c.no_result_reason
              - else
                - points = @is_rifle_cup_series ? (c.european_rifle_score || '-') : points_print(c)
                %span{class: emphasize_limit && points.to_i >= emphasize_limit ? 'cup-points__emphasize' : ''}
                  = link_to_unless is_pdf, points, series_competitor_path(c.series, c)
            - else
              \-
        - if @is_rifle_cup_series
          %td.center.total-points= cc.european_rifle_score
        - else
          %td.center.total-points= cup_points_print(cc)

app/views/cup_series/show.pdf.haml
%h1= @cup.name
%h2= "#{@cup_series.name} - #{t :results}"
= render partial: 'cup_series_results', locals: { cup_series: @cup_series, pdf: true }